# Generated by Django 5.0.7 on 2024-07-28 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="habit",
            name="dueDate",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="habit",
            name="status",
            field=models.CharField(
                choices=[("complete", "complete"), ("incomplete", "incomplete")],
                default="incomplete",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(default="", max_length=20),
        ),
    ]
