# Generated by Django 5.0.7 on 2024-07-28 06:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0003_habit_consistency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="dueDate",
        ),
        migrations.RemoveField(
            model_name="habit",
            name="status",
        ),
        migrations.CreateModel(
            name="oneHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dueDate", models.DateField(default=datetime.datetime.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("complete", "complete"),
                            ("incomplete", "incomplete"),
                        ],
                        default="incomplete",
                        max_length=15,
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="health.habit"
                    ),
                ),
            ],
        ),
    ]
